### ISSUE TITLE
Standalone on a Ubuntu Server

### ISSUE THREAD

**Issue by FwSchultz** [mattwright324/maps-let-loose#106]
Hi,
how do i get the page to run permanently. if i close the terminal the page is off of course. 
But I would like to have it online permanently.

could you help me there.

with the command bundle exec jekyll serve --host 123.45.67.8 --port 4000
the page starts but even after closing the terminal the page goes offline.

**Comment by mattwright324** [comment]
Hey @FwSchultz 

I've never used Jekyll for permanent local apps but I'm sure its possible. Potentially you could achieve what you want by...

- Creating a [systemd service](https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units) that runs that jekyll serve command
- If it doesn't work as easy as a service, extend the service idea by having it
    - Run the serve command via an sh script
    - Run the serve command in a screen from an sh script

Probably helpful, found this

- [Setting Up Jekyll to run as a systemd service -- with gotchas solved](https://jeremyhajek.com/2022/05/28/Setting-Up-Jekyll-to-run-as-a-systemd-service.html)

**Comment by FwSchultz** [comment]
Perfect with your link "Setting Up Jekyll to run as a systemd service -- with gotchas solved" it now runs as a standalone.

Thanks for that
