### ISSUE TITLE
Default garrison overlays

### ISSUE THREAD

**Issue by realist-hll** [mattwright324/maps-let-loose#29]
Thanks for making this, it looks very promising!

May I request two garrison overlays, one for each of Axis/Allied offensive mode, and a "flip" checkbox, à la arty overlays?

**Comment by mattwright324** [comment]
Hey @realist-hll,

That's a good idea and can be done though can also see value in having both sides visible at time same time, can figure out a way to do both

**Comment by mattwright324** [comment]
This is now a thing, converted the simple image overlays to non-interactable elements and now default offensive garrisons (along with arty, tanks, and repair stations) can be toggled to see all at once or only one side. Side A, Both, and Side B

**Comment by mattwright324** [comment]
to be useable for offensive planning, the set of default garrisons on the blue side will be hidden when captured sectors are enabled even when 'both' defaults are enabled
