### ISSUE TITLE
Exporting to png ignores sector colors.

### ISSUE THREAD

**Issue by Aimless321** [mattwright324/maps-let-loose#42]
First of all really awesome tool! Helps us a lot with making strats.

One thing i noticed today is that the sector colors are not visible when you export a map.
So in the editor it looks like this: 
![image](https://user-images.githubusercontent.com/6079485/193401993-a267a7d8-b23c-40fd-89d5-235ccfd85a5a.png)

But the exported png ends up looking like this:
![SMDMV2_Custom_MLL(1)](https://user-images.githubusercontent.com/6079485/193402011-28af98da-cc84-40fa-92f8-81bb64616504.png)

**Comment by mattwright324** [comment]
Hi @Aimless321 

Thanks, this does seem to be the case. I must have removed a couple lines for the save-as-png canvas that I shouldn't have, it should be a quick fix.

**Comment by mattwright324** [comment]
This should be fixed now, thanks! I accidentally had the code for the save-as-png in the export-to-zip and just had to move it.
